name: 'real_estate_project'
version: '1.0'
profile: 'real_estate_project'

model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [data]
macro-paths: [macros]
snapshot-paths: [snapshots]
target-path: target  # directory which will store compiled SQL files
clean-targets:  # directories to be removed by `dbt clean`
  - target
  - dbt_modules
# Configuring models by folder
models:
  real_estate_project:
    
    staging:
      +schema: 'staging'  # Will create models in the 'staging' schema
      +materialized: view  # Typically, staging models are views

    # Configuration for models in the 'final' folder
    final:
      +schema: 'final'  # Will create models in the 'final' schema
      +materialized: table  # Final models are usually stored as tables
